webtalk_init -webtalk_dir E:/Nekrasov Vladiimir/CNN_project_start/CNN_project_start.sim/sim_1/behav/xsim/xsim.dir/MaxpoolS1_testbench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec  1 14:24:13 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2f315388-2a91-4e69-ac24-4b70748b5cca" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5cbd0fb9094e4a1fa2b899db39a523d0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3691 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1902091500 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "11" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.36_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15368_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2191859608 -regid "" -xml E:/Nekrasov Vladiimir/CNN_project_start/CNN_project_start.sim/sim_1/behav/xsim/xsim.dir/MaxpoolS1_testbench_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Nekrasov Vladiimir/CNN_project_start/CNN_project_start.sim/sim_1/behav/xsim/xsim.dir/MaxpoolS1_testbench_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Nekrasov Vladiimir/CNN_project_start/CNN_project_start.sim/sim_1/behav/xsim/xsim.dir/MaxpoolS1_testbench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
