# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/NekrasovVladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'design_1_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/NekrasovVladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/NekrasovVladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/NekrasovVladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'design_1_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/NekrasovVladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/NekrasovVladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
