@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jun 15 17:18:50 +0300 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim CTRL_machine_testbench_behav -key {Behavioral:sim_1:Functional:CTRL_machine_testbench} -tclbatch CTRL_machine_testbench.tcl -protoinst "protoinst_files/design_1.protoinst" -view E:/NekrasovVladiimir/CNN_project_start/CTRL_machine_testbench_behav.wcfg -log simulate.log"
call xsim  CTRL_machine_testbench_behav -key {Behavioral:sim_1:Functional:CTRL_machine_testbench} -tclbatch CTRL_machine_testbench.tcl -protoinst "protoinst_files/design_1.protoinst" -view E:/NekrasovVladiimir/CNN_project_start/CTRL_machine_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
