# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Nekrasov Vladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/ip/FIFO_for_MaxpoolS1/FIFO_for_MaxpoolS1.xci
# IP: The module: 'FIFO_for_MaxpoolS1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Nekrasov Vladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/ip/FIFO_for_MaxpoolS1/FIFO_for_MaxpoolS1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_for_MaxpoolS1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Nekrasov Vladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/ip/FIFO_for_MaxpoolS1/FIFO_for_MaxpoolS1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_for_MaxpoolS1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Nekrasov Vladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/ip/FIFO_for_MaxpoolS1/FIFO_for_MaxpoolS1.xci
# IP: The module: 'FIFO_for_MaxpoolS1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Nekrasov Vladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/ip/FIFO_for_MaxpoolS1/FIFO_for_MaxpoolS1.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_for_MaxpoolS1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Nekrasov Vladiimir/CNN_project_start/CNN_project_start.srcs/sources_1/ip/FIFO_for_MaxpoolS1/FIFO_for_MaxpoolS1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_for_MaxpoolS1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
